<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[tc is success]]>
    </line>
    <line>
      <![CDATA[tc is failed,screenshot taken]]>
    </line>
  </reporter-output>
  <suite started-at="2022-06-21T14:18:47 IST" name="Default suite" finished-at="2022-06-21T14:18:47 IST" duration-ms="100">
    <groups>
    </groups>
    <test started-at="2022-06-21T14:18:47 IST" name="Default test" finished-at="2022-06-21T14:18:47 IST" duration-ms="100">
      <class name="testNGlistener.MyTestClass">
        <test-method signature="MyTest()[pri:0, instance:testNGlistener.MyTestClass@2805d709]" started-at="2022-06-21T14:18:47 IST" name="MyTest" finished-at="2022-06-21T14:18:47 IST" duration-ms="14" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[tc is success]]>
            </line>
          </reporter-output>
        </test-method> <!-- MyTest -->
        <test-method signature="MyMethod()[pri:0, instance:testNGlistener.MyTestClass@2805d709]" started-at="2022-06-21T14:18:47 IST" name="MyMethod" finished-at="2022-06-21T14:18:47 IST" depends-on-methods="testNGlistener.MyTestClass.MyTest" duration-ms="5" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at testNGlistener.MyTestClass.MyMethod(MyTestClass.java:23)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[tc is failed,screenshot taken]]>
            </line>
          </reporter-output>
        </test-method> <!-- MyMethod -->
      </class> <!-- testNGlistener.MyTestClass -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
